### ISSUE TITLE
[BUG] brw3 kleur  aanpassen

### ISSUE THREAD

**Issue by Timekuh** [Hulpdiensten-Centraal/HDC_Development#2]
**Beschrijving van de bug**
De kleur is te donker en er zitten groenen strepen tussen.

**Stappen om te reproduceren**
-

**Screenshots**
-

**FiveM informatie (vul alsjeblieft de volgende informatie in):**
- Cache al geleegd?  Nee
- Komt dit op een speciale locatie voor? Nee
- Staat er een error in F8? Nee

**Extra context**
-

**Foto van F8**
-

**Logs**
-

**Discord**
Gewoontim_

**Comment by reiniervg** [comment]
Ha tim,
Goed dat je dit vermeld. Ik ga dit gelijk laten oppakken door daniel die zal dit z.s.m aanpassen en zal je een terugkoppeling geven.

@danielriemslag  ^
