### ISSUE TITLE
[BUG] Code ROOD!!!!

### ISSUE THREAD

**Issue by Jackey0001** [Hulpdiensten-Centraal/HDC_Development#3]
**Beschrijving van de bug**
Een heldere en beknopte beschrijving van de bug.
Wanner ik /dildo doe, werkt het niet. 

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '....'
3. Scroll naar beneden naar '....'
4. Zie foutmelding

**Verwacht gedrag**
Een duidelijke en beknopte beschrijving van wat je had verwacht te gebeuren.

**Screenshots**
Indien van toepassing, voeg screenshots toe om het probleem uit te leggen.

**FiveM informatie (vul alsjeblieft de volgende informatie in):**
- Cache al geleegd? [Ja/Nee] Ja
- Komt dit op een speciale locatie voor? [bijv. P81] Postcode 4335
- Staat er een error in F8? [Ja/Nee] Ja

**Extra context**
Voeg hier eventuele andere context over het probleem toe.

**Foto van F8**
Voeg hier een foto van de laatste regels in F8 toe, zodat we kunnen controleren of het om een fout in een script gaat.

**Logs**
Het zou ook handig zijn om een logbestand naar Reinier te sturen. Dit kan je doen door op de F8 knop te drukken, vervolgens op de blauwe knop rechts "Open log" te klikken en het bestand naar Reinier te sturen, samen met de link naar de issue op GitHub. [Discord Profiel](https://discord.com/users/528557003770167297)

**Discord**
Wat is je discord? zo kunnen we je achteraf bereiken als we nog wat vragen over deze bug hebben. JohnB__

**Comment by reiniervg** [comment]
Ik zie het al, Code zwart!

@danielriemslag  Hoe kan hij zijn cache legen?
