### ISSUE TITLE
[BUG] [Tankscript brengt je brandsof percentage naar 1%]

### ISSUE THREAD

**Issue by Timekuh** [Hulpdiensten-Centraal/HDC_Development#9]
**Beschrijving van de bug**
Als je gaat tanken dan gaat je brandstof percentage naar 1%

**Stappen om te reproduceren**
ga naar tankstation
pak de tank pomp
ga tanken
en dan gaat je brandstof percentage naar 1%

**Verwacht gedrag**
Dat het word opgelost

**Screenshots**
-
**FiveM informatie (vul alsjeblieft de volgende informatie in):**
- Cache al geleegd? Ja
- Komt dit op een speciale locatie voor? Nee
- Staat er een error in F8? Ja
- Hebben andere hier ook last van? Ja

**Foto van F8**
.
![Schermafbeelding 2024-03-12 145631](https://github.com/Hulpdiensten-Centraal/HDC_Development/assets/161977473/2781137e-048f-43c4-b6e0-8782461b53a7)

**Logs**
-
**Discord**
Wat is je discord? zo kunnen we je achteraf bereiken als we nog wat vragen over deze bug hebben.
gewoontim_

**Comment by reiniervg** [comment]
Ga ik oppakken.

**Comment by reiniervg** [comment]
Opgelost.

**Comment by reiniervg** [comment]
Blijkt toch niet opgelost te zijn, meer mensen hebben hier last van.
Ik ga even kijken of ik dit kan regelen.

**Comment by reiniervg** [comment]
Opgelost, script tijdelijk uit de server omdat er meer problemen mee zijn.
